FROM python:3.9

RUN pip install mlflow

COPY . /app
# Affiche le répertoire courant
RUN pwd

# Affiche seulement 2 niveaux de l'arborescence à partir du répertoire courant
RUN find . -maxdepth 2

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "/mlflow/mlruns", "--default-artifact-root", "/mlflow/mlruns"]
