FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pwd
COPY . /app
RUN pwd
RUN find . -maxdepth 2
WORKDIR /app/app
RUN pwd
# Affiche seulement 2 niveaux de l'arborescence


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
